name: Production deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        sudo apt-get -y update && sudo apt-get -y install \
          build-essential \
          zlib1g-dev \
          libssl-dev \
          libncurses-dev \
          libffi-dev \
          libsqlite3-dev \
          libreadline-dev \
          libbz2-dev \
    - run: |
        pip install --user \
          awscli \
          awsebcli \
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ secrets.aws_region }}
    - name: Create file with app version
      run: echo "aeroenvio-api-${GITHUB_SHA}" > version.txt
    - name: Stage file with app version
      run: git add version.txt
    - name: Print repo status
      run: git status
    - name: Print eb version
      run: eb --version
